; MiniGO.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGO.java
.class public MiniGO
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 6
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 1
  .limit locals 1
  .line 8
  0: ldc "Hello World 1!"
  2: invokestatic io/putStringLn(Ljava/lang/String;)V
  .line 9
  5: return
.end method


